### ISSUE TITLE
Comments between 'mainImage' function name and body break compilation

### ISSUE THREAD

**Issue by 57ar7up** [stevensona/shader-toy#107]
I don't need them, but it's not easy to find where error is
Not working:
```
void mainImage() /**/ {
}
```
```
void mainImage() //
{
}
```

**Comment by Malacath-92** [comment]
Thanks for bringing this up. Almost feels like you're fuzzing the extension with some human input  😄 

In the section [Compatibility with Shadertoy.com](https://github.com/stevensona/shader-toy#compatibility-with-shadertoycom) it is explained how a valid `void mainImage` is found in source code
> The definition of `void main()` is found by matching the regex `/void\s+main\s*\(\s*\)\s*\{/g`
So from that it is not surprising that comments will ruin your day.

However, this is a leftover of the extension before it had an integrated glsl parser, so it should be possible now to actually find a real definition of `void mainImage()` and `void main()`
I'll take a look after work

**Comment by 57ar7up** [comment]
Actually, there is much more to it, because following works on ShaderToy:
`#define mainImage(o,u)o=vec4(1.);` 
And this
```
#define mainImage(o,u)\
	o=vec4(1.);
```
😄

**Comment by Malacath-92** [comment]
Sorry that I never followed up on this. While we have a functioning parser/lexer for glsl I don't think we want to really determine if a symbol `mainImage` is defined approriately. The current behaviour is intended to ease transition from shadertoy.com to VSCode ShaderToy, not to make them equivalent. So I wouldn't mind if people have to "hack" their way around what is already a "hack" for the sake of using fewer symbols on shadertoy.com
The error for a missing `mainImage` in the file can come with a note of how to circumvent it the way you did, but also this will not work for much longer, since we will eventually use the parser/lexer to find an actual definition of `mainImage` in code, so comments will be skipped when that happens. Maybe I will add code to find `#define mainImage` as well, but I can't guarantuee that.

**Comment by Malacath-92** [comment]
I've played around with this a bit recently. While I could throw together a decently functional preprocessor and use that in conjunction with our existing parser to find any valid definition for `mainImage` and `main` I don't feel like the complexity added to the code base is really worth these corner cases that in the end are easily worked around either way.
So I am considering rather to add a hard-compatibility mode with shadertoy.com for the people that really want that kind of stuff. Meaning you enable that in the options and if you do we will just assume your shaders define `mainImage` and at that point you can do whatever crazy stuff you want. This would add next to no complexity to the codebase and probably satisfies more people than a half-functional preprocessor would anyways.

**Comment by 57ar7up** [comment]
> So I am considering rather to add a hard-compatibility mode with shadertoy.com for the people that really want that kind of stuff. Meaning you enable that in the options and if you do we will just assume your shaders define `mainImage` and at that point you can do whatever crazy stuff you want. This would add next to no complexity to the codebase and probably satisfies more people than a half-functional preprocessor would anyways.
Seems like a right way
