### ISSUE TITLE
Wrong attribution

### ISSUE THREAD

**Issue by alxklk** [stevensona/shader-toy#110]
I was surprised to found my shader from https://www.shadertoy.com/view/XsVSzW among the demos of your shader-toy project for VS Code https://github.com/stevensona/shader-toy/blob/master/demos/plasma1.glsl with attribution to S.Guillitte.
As You can see, the sources are the same, if skip the attribution. Could you remove that wrong attribution?

**Comment by Malacath-92** [comment]
I'm super sorry, we should always link to the sources on shadertoy.com to make sure we give the right attribution. But I never made a pass to make sure that this is updated for our older examples.
Unfortunately I don't have any reliable access to push any changes until next week, so if this feels urgent to you I would encourage you to create a pull request with the attribution changes.
Otherwise I will do a pass on all shaders that we didn't create ourselves and unify the attributions as well as double check if they are correct.

**Comment by stevensona** [comment]
My apologies for that, @alxklk. Thanks for bringing to our attention.
