### ISSUE TITLE
Can not control filter and wrap mode for buffer input 

### ISSUE THREAD

**Issue by letmaik** [stevensona/shader-toy#114]
https://www.shadertoy.com/view/XsyGzz

![grafik](https://user-images.githubusercontent.com/530988/93708380-9c251f00-fb2d-11ea-8cc4-d0e9342d081b.png)

![grafik](https://user-images.githubusercontent.com/530988/93708390-a5ae8700-fb2d-11ea-93cf-51296d4e078d.png)

**Comment by letmaik** [comment]
Nevermind, I was missing the texture...

**Comment by Malacath-92** [comment]
You can get something similar with self-feedback:
![image](https://user-images.githubusercontent.com/30243536/93720029-c3f4a100-fb86-11ea-8ae2-f18517aa9fbe.png)

The issue here is that reading from other buffers by default uses nearest sampling, which will result in the distortions you see here. If you go on the online version and change the sampling to nearest you get the same effect. So I'm renaming the issue to something more fitting.

**Comment by theetcher** [comment]
Want to bump up this request. Just faced this behavior. For channels which result is other shader: MagFilter and MinFilter always Nearest, WrapMode is always Clamp.

**Comment by Malacath-92** [comment]
Alright, been a busy time since I moved recently. I will try to get back on this project. Thanks for the reminder @theetcher 🙏
