### ISSUE TITLE
"To use relative paths please open a workspace"

### ISSUE THREAD

**Issue by MJCD** [stevensona/shader-toy#25]
I have already saved a new workspace with the glsl file open and saved it, then reopened the workspace - still get this error followed by; 'Unable to open 'GLSL Preview": ENOENT: no such file or directory ...\undefined\other-shader.glsl

**Comment by Malacath-92** [comment]
This issue I introduced in the last release because I did not test the old setup. I made a pull-request to fix this. I would advise you to insert the following snippet into your "settings.json" which you open as described [here](https://code.visualstudio.com/docs/getstarted/settings).
```
    "shader-toy": {
        "useInShaderTextures": true
    },
```
and from now on specify textures in the shader rather than the settings.

**Comment by MJCD** [comment]
Thanks for your prompt response @Malacath-92 - that got me up and running for now. Appreciate your efforts.

**Comment by Malacath-92** [comment]
Said pull-request should have closed the issue actually. Not sure why it didn't.
But now that you're here it wouldn't have hurt to hear it from the horse's mouth :P
I'll close the issue though, no one else seems to have had the issue
