### ISSUE TITLE
improve ShaderToy mode detection

### ISSUE THREAD

**Issue by Trass3r** [stevensona/shader-toy#53]
I'm using the following boilerplate code to make shaders compatible with ShaderToy and standard compilers (that includes VSCode extensions like Shaderc GLSL Linter):
```glsl
//#version 460
precision highp float;

#ifdef STDGLSL
layout(location = 0) in VertexData
{
	vec4 v_position;
	vec3 v_normal;
	vec2 v_texcoord;
};
layout(location = 0) out vec4 fragColor;
layout(binding = 0) uniform ShadertoyBlock
{
	vec3 iResolution;
	float iGlobalTime;
	float iTimeDelta;
	int iFrame;
	vec4 iMouse;
	vec4 iDate;
	float iSampleRate;
};
float iTime = iGlobalTime;
uniform sampler2D iChannel0;
uniform sampler2D iChannel1;
uniform sampler2D iChannel2;
uniform sampler2D iChannel3;

void mainImage(out vec4, in vec2);
void main(void) { mainImage(fragColor, v_texcoord * iResolution.xy); }
#else
#iChannel0 "file://./text.png"
#endif
```
This works quite nicely but there are 2 issues:
* Had to change `main()` to `main(void)`, otherwise your regex would pick it up and not generate its own main. Should be documented or improved (better preprocessor handling).
* I can't use the version directive obviously (can't ifdef it). It only works because the shaderc extension offers an option for defining it via the commandline. Any ideas?

**Comment by Malacath-92** [comment]
Thanks for bringing up these issues  👍 

Considering your first point. Imho it is far beyond the scope of this extension to implement a real preprocessor rather than the stupid string finding thing we have. The code inserted before compilation, not just by us, might contain more preprocessor directives that we can't really know about. Just speculating here though, I'd need to read more about this stuff. If we know more about this we can rethink if it's worth it to make a better preprocessor, but I doubt so.
So I would vote for documenting how the automatic generation of `void main()` works and make clear that using `void main(void)` is an actual backdoor to defining a main that doesn't prevent generation of it. What do you think?

Considering the `#version` directive, it should be quite simple to look for it on line 1 and reserve its space in the transformed shader and move it back to line 1. I can look into that later this week.

Keep the suggestions coming if you have more problems  😃

**Comment by Trass3r** [comment]
1. Yes I agree.
2. Wouldn't it be easier and also necessary to replace the version directive? For WebGL2 you probably need `300 es` right? While the linter needs `310 es` at least to generate SPIR-V from ES at all and `320 es` or `440` for all the features like input blocks.

**Comment by Malacath-92** [comment]
> 1. Yes I agree.

Then I'll fix that for the next version
> 2. Wouldn't it be easier and also necessary to replace the version directive? For WebGL2 you probably need `300 es` right? While the linter needs `310 es` at least to generate SPIR-V from ES at all and `320 es` or `440` for all the features like input blocks.

Quite honestly I wasn't quite sure what versions are supported (or necessary) for WebGl and WebGL2, I wanted to take a look at the specifications when I have more time on the weekend. If a user provided `#version` is ignored/replaced, it sounds like something the user should be told. So maybe if this is how it will work a message should be displayed (that can be disabled in settings). I'll look more at it on the weekend. Or if you have a clear idea of it already and the time to spare you can draft a PR.

> Yeah I see, [here](https://github.com/stevensona/shader-toy/blob/ace8b2bdcaf05abc64498cada3accd71fd238259/src/webviewcontentprovider.ts#L205) and [there](https://github.com/stevensona/shader-toy/blob/ace8b2bdcaf05abc64498cada3accd71fd238259/src/webviewcontentprovider.ts#L261)

Good catch  😃
I wasn't consciously aware that includes were compiled with an explicit `#version`, but from what you say it would make sense to do this. However since the extension should also support WebGL and not just WebGL2, it might be necessary to pick that depending on what's available?

> Also looks like `iGlobalFrame` is missing. By the way I guess you could simplify your code a bit by using some defines in `shaderPreamble` like
> 
> ```c
> #define iGlobalTime iTime
> #define iGlobalFrame iFrame
> ```

Wasn't aware of `iGlobalFrame`, that should be easy to add. Using the preprocessor for these is also a good idea  👍

**Comment by Trass3r** [comment]
> Quite honestly I wasn't quite sure what versions are supported (or necessary) for WebGl and WebGL2, I wanted to take a look at the specifications when I have more time on the weekend.

Unfortunately only up to `300 es`.

> If a user provided `#version` is ignored/replaced, it sounds like something the user should be told.

Maybe some squiggles in the editor.

> I wasn't consciously aware that includes were compiled with an explicit `#version`, but from what you say it would make sense to do this. However since the extension should also support WebGL and not just WebGL2, it might be necessary to pick that depending on what's available?

It would have to be a quite old VSCode version to not support WebGL2.

**Comment by Malacath-92** [comment]
> Unfortunately only up to `300 es`.

If that's both WebGL and WebGL2 then it's simple to do though.
 
> Maybe some squiggles in the editor.

Good idea again, I'll take a look.

> It would have to be a quite old VSCode version to not support WebGL2.

Risking to sound like an idiot here, but can't that be dependent on drivers rather than just VSCode? There's no question for VSCode supporting it because we require a version new enough for using WebView already.

**Comment by Trass3r** [comment]
> If that's both WebGL and WebGL2 then it's simple to do though.

WebGL is 100 only.

> Risking to sound like an idiot here, but can't that be dependent on drivers rather than just VSCode? There's no question for VSCode supporting it because we require a version new enough for using WebView already.

I'm not sure if that can actually happen, Chromium uses ANGLE to translate it to DirectX iirc so it should be well supported.

**Comment by Malacath-92** [comment]
> Chromium uses ANGLE to translate it to DirectX iirc so it should be well supported.

And what happens on Linux and OSx?

**Comment by Trass3r** [comment]
Yeah it just occurred to me it's cross-platform after all 😅

**Comment by Malacath-92** [comment]
I added a couple lines to ignore the version directive, it's shown by green squiggles that they are ignored.
For now I avoided inserting version directives because it caused some issues to do naïvely.
Also documented the case of `void main(void)`
Lastly add `iGlobalFrame` by your suggestion.
