### ISSUE TITLE
Expose widgets(slider, x-y, color picker) for graphical control of shader inputs/uniforms

### ISSUE THREAD

**Issue by yafacex** [stevensona/shader-toy#55]
Is it hard to export uniforms(float,vec2,vec3) as 1d-slider or 2d-position-picker or 3d-color-picker  for easy edit?

**Comment by Malacath-92** [comment]
It's a feature I've been thinking about for quite a while, but I still don't know how much work it actually is. Mainly because a large part of it is actually writing the interface, which I am least proficient in, out of the disciplines this extension needs to work. Regarding the "backend" I am quite confident this is possible to do.
@stevensona do you have any input on this, regarding the feasibility of it?

**Comment by stevensona** [comment]
Definitely doable.

That said, there are some design/ux questions that would need to be answered first.

**Comment by Malacath-92** [comment]
That's what I expected. I'll try to collect my thoughts on it and maybe get some examples.

**Comment by Malacath-92** [comment]
The extension [glsl-canvas](https://github.com/actarian/vscode-glsl-canvas) does something similar.
![image](https://user-images.githubusercontent.com/30243536/59145660-36b82800-89e7-11e9-8260-e7cf8f89fbc2.png)


 - They expose simply N sliders for N-dimensional objects and let the user modify those. This could be much nicer with position-, color- and color-alpha-pickers.
 - To use the user defined uniforms the user has to additionally place a uniform declaration in their shader. Since we are already doing significant transforms of the source code, we could simply provide this declaration.
 - To get to the sliders you need to press the third button on the bottom and then a button on the top right. I certainly thing this is one extra step. If user added uniforms they very well will be fine with having an additional button available.
 - In keeping with the spirit of our extension, I'd assume enabling users to define uniforms in the shader would be good. Though I can see the case of a user wanting to add uniforms that they always have accessible for quick prototyping/testing. The exact syntax for defining a uniform, I am not sure about, but probably something along the lines of `#iMyUniform vec3` could be simple enough, expanding it with initial values in the future.
 - I don't see a reason to allow only floating-point uniforms either. From the backend perspective adding integer uniforms should be quite trivial. From a frontend, I have of course no idea if integer sliders and "color" pickers are a good thing or not. Alternatively those could simply be input using text fields.

Those are my quick thoughts on this.

**Comment by Malacath-92** [comment]
[dat.gui](https://github.com/dataarts/dat.gui) looks exactly like what we need. It also looks like that's what glsl-canvas is using, so it should be familiar/easy for users. I'll invest some time into this, unless you're already on it @stevensona

**Comment by stevensona** [comment]
Oh, dat.gui is perfect! By all means, go ahead--I hadn't made much progress yet.

**Comment by Malacath-92** [comment]
@yafacex have you had any chance to test the current experimental support for custom uniforms?

**Comment by Malacath-92** [comment]
Closing this since we didn't receive any input to suggest that it's not sufficient. If someone wishes more features than what we currently have they should probably open a new issue anyways.
