### ISSUE TITLE
Texture setting support

### ISSUE THREAD

**Issue by tomorrowevening** [stevensona/shader-toy#61]
Adding support for the channel's filter & wrap modes would be fantastic 👍

**Comment by Malacath-92** [comment]
Yes, I agree this would be a good feature. I have difficulties though imagining a good UX for this, considering we try to keep all setup contained in the shader. A couple of possibilities:
 - Specify filter and/or wrap mode with the definition of the channel, e.g.
```
#iChannel0 "file://./tex.png?wrap=clamp&filter=nearest"
```
 - Specify filter and/or wrap separatedly from the channel definition:
```
#iChannel0 "file://./tex.png"
#iChannel0Wrap "clamp"
#iChannel0Filter "nearest"
```

I like option 1 because there are libraries readily available to deal with it and it keeps the clutter minimal.
I dislike it though because it is difficult to parse for a human.
I like option 2 on the other hand because imho it is easier to parse for a human and makes it easy to disable by simply putting a comment.
I dislike it because honestly, something just feels off about it. It also gives a wrong impression, that `iChannel0Wrap` would be an available variable. And lastly it complicates the code to parse this.

It's pretty obvious that all of this is pretty subjective, so I'd be happy to hear your thoughts on it, or hear if you have other suggestions on how to do this.

**Comment by tomorrowevening** [comment]
Yep! Completely agree. I prefer something similar to Option 2 for the sake of being able to quickly update settings without breaking the compiler. I considered using structs for a moment, but that defeats why the channels are defined in the first place... so, whatever you prefer :)

**Comment by tomorrowevening** [comment]
🙌
