### ISSUE TITLE
support for texture arrays, MRT, integer textures, image load/store?

### ISSUE THREAD

**Issue by bernief1** [stevensona/shader-toy#62]
hi, i just came across your project - nice!
i'm currently working on something similar to help me with my lightmapping / path tracing research. i'd be interested in collaborating. here's the list of features beyond what ShaderToy supports that i'm currently supporting:

texture arrays
volume textures
multiple rendertargets
up to 32 texture inputs per pass
arbitrary texture resolutions
all GPU-supported texture formats
image load/store (and atomics)
arbitrary number of passes
slider widgets defined in metadata and rendered as an overlay
all declarations in metadata in the shader code .. e.g. to create a 1024x1024 buffer you just write "//$BUFFER:mybuffer,w=1024,h=1024" in the shader code, and then you can sample it with "texture(mybuffer,...)" etc.

send me an email if you are interested in sharing ideas or unifying our syntax!
bernie.freidin@gmail.com

**Comment by stevensona** [comment]
@bernief1 Is your project public and/or open-source?

**Comment by bernief1** [comment]
I threw it on github (I don't normally use github so forgive me if there
are any issues).
You will need two repositories to compile:

https://github.com/bernief1/common
https://github.com/bernief1/shader_toy_player

And you will need to copy the following dll to somewhere in your path (e.g.
C:\Windows)

*common\GraphicsTools\external\glut\freeglut\bin\x64\freeglut.dll*
Then, assuming you have visual studio 2017, you should be able to compile
the .sln.
For commandline args, just pass it the path of the directory containing the
.glsl files you want to run, e.g. "shaders\Underwater_Fractal_Creature"

Let me know if this works!

B

**Comment by Malacath-92** [comment]
You're missing some libraries in your repo, so I can't actually build it without searching for the right versions myself.

Regardless of that, it sounds like you have a set of really nice features. However I don't see how the projects can benefit from each other. The fact alone that one project is written in TypeScript/HTML and the other is written in C++ makes most efforts to port features very non-trivial. On top of that one works based on WebGL, the other on the full OpenGL feature set.

I don't say this to be discouraging or mean, I just honestly think that the two projects live in very different domains, where they each are completely valid and valuable solutions.

When you speak of unifying syntax, of course this is a different question and could bring value to users who might not always be able to use one or the other solution. Thus having a standalone desktop version of shader-toy that obeys the same syntax as the VSC integrated version (and partially the online version) could help a lot. On a side note though, we have many active users on this extension, thus radically changing our syntax would be dangerous.

For now, if you are interested in growing your project and making it inviting to contributors, I would suggest you to clean up the repo a bit, introduce a build-system, make the code portable (if it isn't already), eventually introduce CI and testing. I'd be happy to spend some time to help you with that, because I think having a desktop version of shadertoy is an amazing prospect.

**Comment by bernief1** [comment]
Sure, I'd be interested in help cleaning up the repo so that it's more
usable. I have little experience sharing code outside of the game projects
I've worked on.

First off - which libraries am I missing? Besides OpenGL, the project
depends on FreeImage, GLUT (freeglut), and GLEW. All of these should be in
the *common\GraphicsTools\external\ *directory (which should be parallel to
the *shader_toy\* directory). The settings in the vcxproj specify
additional include and library directory "..\common\;" so the #includes and
#pragma comment(lib,..)'s can find the appropriate files. As I mentioned,
you need to copy the freeglut dll from
*common\GraphicsTools\external\glut\freeglut\bin\x64\freeglut.dll* to
somewhere in your PATH such as C:\Windows - or I suppose you could copy it
to *shader_toy\* directly .. in my local setup I have a common directory
and then many separate projects which use freeglut so I didn't want to have
to duplicate the dll all over the place.

**Comment by bernief1** [comment]
Just to clarify .. the files should be located as follows (this is a subset
of the actual file list for illustration only):
(C:\dev\projects\ is where I have my projects but of course this can be
anything - all file paths are relative)

C:\dev\projects\common\common\common.h
C:\dev\projects\common\GraphicsTools\external\FreeImage\FreeImage.h
C:\dev\projects\common\GraphicsTools\external\FreeImage\x64
C:\dev\projects\common\GraphicsTools\external\FreeImage\x64\FreeImage2015Lib.lib
C:\dev\projects\common\GraphicsTools\external\FreeImage\x64\FreeImage2015Libd.lib
C:\dev\projects\common\GraphicsTools\util\camera.cpp
C:\dev\projects\common\GraphicsTools\util\camera.h
C:\dev\projects\common\GraphicsTools\util\color.h
C:\dev\projects\common\GraphicsTools\util\crc.cpp
C:\dev\projects\common\GraphicsTools\util\crc.h
C:\dev\projects\common\vmath\vmath.cpp
C:\dev\projects\common\vmath\vmath.h
C:\dev\projects\common\vmath\vmath_box.cpp
C:\dev\projects\common\vmath\vmath_box.h
C:\dev\projects\shadertoy_player\shadertoy_player.cpp
C:\dev\projects\shadertoy_player\shadertoy_player.sln
C:\dev\projects\shadertoy_player\shadertoy_player.vcxproj
C:\dev\projects\shadertoy_player\shadertoy_player.vcxproj.filters

**Comment by Malacath-92** [comment]
In particular I fail linking against the static libraries for FreeImage 'GraphicsTools/external/FreeImage/x64/FreeImage2017Lib.lib'

**Comment by bernief1** [comment]
You fail because the file doesn't exist in the correct location? It's in my
repo -  https://github.com/bernief1/common
Did you check that the file locations are correct? In the last email I
sent, I gave a bunch of file location examples.

I apologize for any difficulties getting my repro to compile - I'm not used
to sharing my code. I promise you that all the libraries are there in the
two repos. Can you send me your error, and also run a *dir /S /B* from the
parent directory that you put shader_toy in so I can see all the files are
there?

**Comment by Malacath-92** [comment]
No, there is no static library for FreeImage in your repo. It should be in [this](https://github.com/bernief1/common/tree/master/GraphicsTools/external/FreeImage) folder

**Comment by bernief1** [comment]
Ah - my mistake! I'm sorry I'm not used to github. When I try to copy the
files over it complains that they are over 25MB.

I've zipped up both the shader_toy and common directories and uploaded them
to cloud storage here:
https://www.amazon.com/clouddrive/share/jBVV3yA1PlkWSTNGvkeneBJfSbcniLz48j0oQR5vwqS

**Comment by Malacath-92** [comment]
Closing this since the conversation doesn't belong here, as mentioned previously.
@bernief1 I'm sorry this slipped my mind. If you are still interested in making your repo more open-source friendly just get in touch, I should have some time to help you.
