### ISSUE TITLE
Make compatible OpenGL glsls version 330 ?

### ISSUE THREAD

**Issue by arjankuijpers** [stevensona/shader-toy#7]
I don't know if it is possible to make this awesome plugin compatible with (Desktop) OpenGL.
I am creating shaders for desktop GLSL and they don't seem to display without modifications.

**Comment by stevensona** [comment]
Unfortunately, Visual Studio Code is based on Electron, which is powered by Chromium. Because of this, we're limited to using the "subset" of OpenGL that runs in the browser via WebGL. As it turns out, "A WebGL implementation must only accept shaders which conform to The OpenGL ES Shading Language, Version 1.00" [source](https://www.khronos.org/registry/webgl/specs/1.0/#4.3).

I'm in the planning stages of a desktop-based GLSL shader editor, but it won't be able to run within Visual Studio Code. In the mean time, there is something called "Shadron" which costs $20, and there may be several other free alternatives floating around.

**Comment by Malacath-92** [comment]
If the hardware supports it, then this extension currently supports WebGl 2.0, that's the best we can do.
