### ISSUE TITLE
[BUG] iUniform parse error

### ISSUE THREAD

**Issue by jcyuan** [stevensona/shader-toy#93]
2 problems:

1, if you write some `vec4` `iUniform` type, it makes your shader stops from working, see the GUI panel, it has only the first uniform, and even there is no error at all! :
![image](https://user-images.githubusercontent.com/850854/80756048-77231600-8b64-11ea-9781-795d0f2dc452.png)

and if you remove all the `vec4` (in the red rectangle of the pic) or change them to `const`, other parameters appears again.
![image](https://user-images.githubusercontent.com/850854/80756462-2364fc80-8b65-11ea-9057-0f65f7a3b9fb.png)

2, you can't write float number as ".2" for 0.2 for the iUniform type, it will brings error:
![image](https://user-images.githubusercontent.com/850854/80756547-50b1aa80-8b65-11ea-9929-ab4761f0c8d6.png)

cool tool, thanks so much.

**Comment by jcyuan** [comment]
ah right, `iUniform float abc = -0.5` error.

**Comment by Malacath-92** [comment]
Thanks for bringing up the bugs. But generally, please create separate issues for reporting multiple bugs.
Since this feature requires us to parse parts of the code ourselves it's very possible we just didn't cover all cases. So I'll check to parse floating point numbers correctly, covering all corner cases.
The issue with vec4 is less obvious, I'll see what I can do.
I'm happy to get issues reported for uniforms, since those are still somewhat experimental.

**Comment by jcyuan** [comment]
@Malacath-92 ok sorry. next time will seperate each issues.
