### ISSUE TITLE
[Feature Request] watch changes for included glsl file as well.

### ISSUE THREAD

**Issue by jcyuan** [stevensona/shader-toy#94]
for example 

![image](https://user-images.githubusercontent.com/850854/80785436-d576e580-8bb2-11ea-9172-aeb269c64072.png)

changes in `comm.glsl` better to repreview atutomatically, but I think only `save` action takes effect that's enough.

the main file which has `main` method is good enough now: repreview for every changes.

really great tool, i love it!

**Comment by Malacath-92** [comment]
If I understand you correctly then you could use a static glsl preview on main.glsl and this should already be supported.
With a dynamic preview you wouldn't be able to edit include files without causing those to be previewed (usually resulting in an error) anyways. And having a file change on disk, say because you have it open in another editor and are changing it there, won't result in any callbacks in VSCode. So I'm not sure how this could be improved right now.

**Comment by jcyuan** [comment]
@Malacath-92 hi, sorry for the confusing, i mean:

the preview window is being updated when i modify the code in the `test.glsl` (the main entry file in the pic), this is good.

but when i modify in `comm.glsl` (test.glsl refers some methods in it), the preview does not update.

**Comment by Malacath-92** [comment]
How are you editing comm.glsl, without the preview trying to make that file compile automatically?

**Comment by Malacath-92** [comment]
Besides the fact that I just embarrassingly realized that static previews are not available on the current version due to an error on my part, they do what you want and that is essentially why they were created.
![shadertoy](https://user-images.githubusercontent.com/30243536/80788793-65546980-8b8a-11ea-9b9f-c63bbe9413fc.gif)

**Comment by Malacath-92** [comment]
@jcyuan when #96 goes through, please let me know if the static preview is sufficient for doing what you want.

**Comment by jcyuan** [comment]
looks great! i'll test later and let you know, thanks so much!

**Comment by Malacath-92** [comment]
@jcyuan don't test yet, my PR is still open  :)
So when a new version is deployed (the extension should notify you of that) you can check again

**Comment by jcyuan** [comment]
it works just fine now~ thanks.
